### PR TITLE
Remove threadsafe gem dependency

### PR DESCRIPTION
**Pull request by mperham**
This PR includes the whitespace PR I just sent.  If you merge that PR, you should just see the relevant changes here.

This change removes the thread_safe gem dependency and instead uses a Mutex as a write barrier to ensure multiple threads can't write to the Hash at the same time.

### CODE REVIEW

**Comment by matthewd** [comment]
(I believe) it's unsafe to read a hash at the same time it's being written -- it's not just writes that need the mutex.

cc @thedarkone

**Comment by philr** [comment]
Thanks for submitting the PRs. I hadn't spotted that the thread_safe gem is being deprecated.

Is synchronizing just `Hash` write operations guaranteed to be safe on all Ruby implementations? [`ThreadSafe::Cache`](https://github.com/ruby-concurrency/thread_safe/blob/master/lib/thread_safe/cache.rb) and the replacement [`Concurrent::Map`](https://github.com/ruby-concurrency/concurrent-ruby/blob/master/lib/concurrent/map.rb) use this approach for MRI, but have alternative implementations for JRuby, Rubinius, etc.

**Comment by mperham** [comment]
I wasn't sure if reading was an issue.  The alternative is to pull in concurrent-ruby instead of thread_safe.

**Comment by philr** [comment]
I'm happy with switching from thread_safe to concurrent-ruby.

tzinfo currently has a `required_ruby_version` of `>= 1.8.7`. This would need changing to `>= 1.9.3` to match concurrent-ruby. Some of the code to support Ruby 1.8 in and around [`ruby_core_support.rb`](https://github.com/tzinfo/tzinfo/blob/61fdd4359117e9a406c546bdc044a3e41faaa5d7/lib/tzinfo/ruby_core_support.rb) could also then be dropped.

**Comment by mperham** [comment]
@philr Yeah, you just need to move from ThreadSafe::Hash to Concurrent::Hash.  Exact same semantics.

**Comment by mperham** [comment]
Feel free to close this and do that instead.

**Comment by thedarkone** [comment]
@matthewd is right, technically it is not enough to have synchronization just on the write side. I will readily admit that right now, on all the current Ruby VMs, when run on x86 hardware, synchronization on the read side is not required, but I'm pretty sure that this is going to change on the new gen of runtimes (namely truffle+jruby).

@philr if swapping `thread_safe` for `concurrent-ruby` (`concurrent-ruby` is a larger code base) is not an issue, go for it. `Concurrent::Map` is a carbon copy of `ThreadSafe::Cache`.

PS: @matthewd, thx for the ping.

**Comment by philr** [comment]
@thedarkone thanks for the confirmation regarding write-only synchronization.

The larger code base of concurrent-ruby is unlikely to be an issue. I think the majority of TZInfo users are using it through ActiveSupport and ActiveSupport has already switched to concurrent-ruby for the upcoming Rails 5 release.

I've raised #46 for switching to `Concurrent::Map`.

**Pull request closed without merging**
